### ISSUE TITLE
SETEX with ttlInSeconds <1 fails with "ERR invalid expire time in setex"

### ISSUE THREAD

**Issue by dstaudt** [mokeddes/botbuilder-storage-redis#14]
Using Redis 6.0.5, creating a RedisDbStorage object with ttlInSeconds <1 

Result of .write() is "ERR invalid expire time in setex".  It appears that at least as of Redis 6.0.5 the SETEX 'seconds' parameter must be positive.

I believe simply reverting https://github.com/mokeddes/botbuilder-storage-redis/commit/d01f88c21ffe56cf25ab6965ce6a703839205066 will suffice to fix this.

Note also that the usage example in README.md has a comment re "// data expires in 2 hours", whereas it should either read "data expires in 2 minutes" or have the ttlInSeconds updated to 3600

**Comment by mokeddes** [comment]
@dstaudt  Resolved in the last version !
