### ISSUE TITLE
Read method should not return an item if it is missing in storage.

### ISSUE THREAD

**Issue by Naktibalda** [mokeddes/botbuilder-storage-redis#7]
It caused me unexpected issues in the code which was using MemoryStorage before.
[MemoryStorage](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/memoryStorage.ts#L44-L47) does not return an item if it is missing in the storage.
```js
keys.forEach((key: string) => {
  const item: string = this.memory[key];
  if (item) {
    data[key] = JSON.parse(item);
  }
});
```

[Example](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-core/src/storage.ts#L28-L33) in Storage interface suggests that read returns undefined too.
```JavaScript
const items = await storage.read(['botState']);
const state = items['botState'] || {};
```

So I think that [this code](https://github.com/mokeddes/botbuilder-storage-redis/blob/master/src/redisStorage.ts#L39) is incorrent and should be modified to return only keys that exist in storage.
```js
stateKeys.forEach((key: string, index: number): void => {
  data[key] = JSON.parse(allKeysValuesFromRedis[index] || '{}');
});
```

**Comment by mokeddes** [comment]
Good réflexion.. We will fix this in the next release

**Comment by Naktibalda** [comment]
@mokeddes When are you going to release a new version?
