### ISSUE TITLE
Feature request: expiration time

### ISSUE THREAD

**Issue by Naktibalda** [mokeddes/botbuilder-storage-redis#9]
Conversation state is temporary by its nature - when the conversation ends, that data is no longer useful, but, unless it is explicitly deleted, it stays in storage for a long time, so it wastes memory and/or disk space and can cause compliance issues.
Redis has a nice feature where it is possible to set expiration time of data items (I'm not an expert in Redis), it would really useful if abandoned data would magically disappear few hours later.

I think that the expiration time could be passed as constructor argument to RedisDbStorage and default to 0.
If expiration time is 0, then it would use `set` command, if expiration time is more than 0, it would use setex command with expiration time as second parameter.

Does it look like a good idea?
I can make a pull request.

**Comment by mokeddes** [comment]
Very nice idea .. you can make a pull request !

**Comment by younes-io** [comment]
Hi @mokeddes ,
When do you intend to release this feature ?
Looking forward for your feedback !
Younes.
